#!/usr/bin/env python3
"""
Gamma Presentation Generator with Email
Create and email presentations using Gamma.app API
"""

import os
import sys
import json
import requests
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

def create_and_email_presentation(topic, research_data, recipients):
    """Create presentation and email it to recipients"""
    
    # API configuration
    api_key = "sk-gamma-hClm0HmnAKp1Mo8oM1POPPVqPvJdbH4PJiOrxN8JzTk"
    base_url = "https://public-api.gamma.app/v1.0"
    
    headers = {
        "Content-Type": "application/json",
        "X-API-KEY": api_key,
        "User-Agent": "OpenClaw/1.0"
    }
    
    # Build content
    content = f"""
    {topic}
    
    {research_data}
    
    This presentation covers key findings, market analysis, and practical applications.
    """
    
    # Create presentation
    payload = {
        "inputText": content,
        "textMode": "generate",
        "format": "presentation",
        "textOptions": {
            "language": "en",
            "tone": "professional"
        },
        "numCards": 13,
        "cardSplit": "auto",
        "additionalInstructions": "Create a professional business presentation with clear sections, visual elements, and actionable insights."
    }
    
    try:
        print(f"🎨 Creating presentation about: {topic}")
        response = requests.post(
            f"{base_url}/generations",
            headers=headers,
            json=payload,
            timeout=60
        )
        
        if response.status_code == 201:
            result = response.json()
            generation_id = result.get("generationId")
            print(f"✅ Presentation created: {generation_id}")
            
            # Get email credentials
            gmail_email = os.getenv('GMAIL_EMAIL', 'wotb.spt@gmail.com')
            gmail_password = os.getenv('GMAIL_SMTP_PASSWORD', 'kaho mwqy nwyx sorq')
            
            # Create email
            msg = MIMEMultipart('alternative')
            msg['Subject'] = f"🎨 New Gamma Presentation: {topic}"
            msg['From'] = gmail_email
            msg['To'] = recipients
            
            # Create email content
            gamma_url = result.get("gammaUrl", "")
            
            html_content = f"""
            <html>
            <head>
                <style>
                    body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
                    .header {{ background-color: #6C5CE7; color: white; padding: 20px; text-align: center; }}
                    .content {{ padding: 20px; }}
                    .button {{ display: inline-block; padding: 12px 24px; background-color: #6C5CE7; color: white; text-decoration: none; border-radius: 5px; margin: 20px 0; }}
                    .info {{ background-color: #f8f9fa; padding: 15px; border-radius: 5px; margin: 20px 0; }}
                </style>
            </head>
            <body>
                <div class="header">
                    <h1>🎨 New Gamma Presentation Generated!</h1>
                    <p>{datetime.now().strftime("%B %d, %Y at %H:%M")}</p>
                </div>
                <div class="content">
                    <h2>{topic}</h2>
                    <p>A comprehensive presentation has been automatically generated based on your research topic.</p>
                    
                    <div class="info">
                        <strong>Generation ID:</strong> {generation_id}<br>
                        <strong>Created:</strong> {datetime.now().strftime("%Y-%m-%d %H:%M")}
                    </div>
                    
                    {f'<p><strong>View Presentation:</strong></p><p><a href="{gamma_url}" class="button">Open Presentation</a></p>' if gamma_url else '<p><strong>Status:</strong> Presentation is being processed and will be available in your Gamma dashboard.</p>'}
                    
                    <p><strong>Generated by:</strong> OpenClaw AI Automation</p>
                    <p>This presentation was created automatically using Gamma's AI-powered design tools.</p>
                    
                    <hr>
                    <p><small>You can access all your presentations at <a href="https://gamma.app">gamma.app</a></small></p>
                </div>
            </body>
            </html>
            """
            
            html_part = MIMEText(html_content, 'html')
            msg.attach(html_part)
            
            # Connect to Gmail SMTP
            server = smtplib.SMTP('smtp.gmail.com', 587)
            server.starttls()
            server.login(gmail_email, gmail_password)
            
            # Send email
            text = msg.as_string()
            server.sendmail(gmail_email, recipients, text)
            server.quit()
            
            print(f"✅ Email sent successfully to {recipients}")
            return {
                "success": True,
                "generation_id": generation_id,
                "message": f"Presentation created and emailed to {recipients}"
            }
            
        else:
            print(f"❌ API Error: {response.status_code} - {response.text[:200]}")
            return {
                "success": False,
                "error": f"API returned {response.status_code}",
                "message": "Failed to create presentation"
            }
            
    except Exception as e:
        print(f"❌ Error: {e}")
        return {
            "success": False,
            "error": str(e),
            "message": "Failed to create and email presentation"
        }

if __name__ == "__main__":
    if len(sys.argv) < 4:
        print("Usage: python3 email_presentation.py <topic> <research_data> <recipient_email>")
        print("Example: python3 email_presentation.py 'AI Trends' 'Research about AI...' 'user@example.com'")
        sys.exit(1)
    
    topic = sys.argv[1]
    research_data = sys.argv[2]
    recipient = sys.argv[3]
    
    result = create_and_email_presentation(topic, research_data, recipient)
    print(json.dumps(result, indent=2, ensure_ascii=False))